export enum Gender {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum AnimalSpecies {
  HOLSTEIN_COW = "HOLSTEIN_COW",
  FREISIAN_COW = "FREISIAN_COW",
  ANKOLE_COW = "ANKOLE_COW",
  BROWN_SWISS_COW = "BROWN_SWISS_COW",
  GIROLANDO_COW = "GIROLANDO_COW",
  JERSEY_COW = "JERSEY_COW",
  SAHIWAL_COW = "SAHIWAL_COW",
  LARGE_WHITE_PIG = "LARGE_WHITE_PIG",
  DUROC_PIG = "DUROC_PIG",
  LANDRACE_PIG = "LANDRACE_PIG",
  PIETRAIN_PIG = "PIETRAIN_PIG",
  INDIGENOUS_PIG = "INDIGENOUS_PIG",
  MERINO_SHEEP = "MERINO_SHEEP",
  DORPER_SHEEP = "DORPER_SHEEP",
  LOCAL_GOAT = "LOCAL_GOAT",
  INDIGENOUS_ANKOLE_COW = "INDIGENOUS_ANKOLE_COW",
  INDIGENOUS_GOAT = "INDIGENOUS_GOAT",
}

export enum MessageSentStatus {
  SENT = "SENT",
  DELIVERED = "DELIVERED",
  READ = "READ",
  FAILED = "FAILED",
  LOADING = "LOADING",
}

export enum MessageType {
  TEXT = "TEXT",
  FILE = "FILE",
  IMAGE = "IMAGE",
}

export enum AnimalType {
  COW = "COW",
  GOAT = "GOAT",
  PIG = "PIG",
  SHEEP = "SHEEP",
}

export enum AnimalHealth {
  HEALTHY = "HEALTHY",
  SICK = "SICK",
  RECOVERING = "RECOVERING",
}

export enum AnimalStatus {
  ALIVE = "ALIVE",
  DECEASED = "DECEASED",
  SOLD = "SOLD",
  PREGNANT = "PREGNANT",
  OTHER = "OTHER",
}